GeoCodeurBundle/Entity/AdresseCmt.php
<?php

/**
 * Created by PhpStorm.
 * User: dhaouadi_a
 * Date: 23/11/2016
 * Time: 16:32
 *  Adresse
 */

namespace GeoCodeurBundle\Entity;


use Doctrine\ORM\Mapping as ORM;
use GeoCodeurBundle\Api\CurlCaller;
use GeoCodeurBundle\Controller\DefaultController;

/**
 * @ORM\Table(name="geocode_adresse")
 * @ORM\Entity(repositoryClass="GeoCodeurBundle\Repository\AdresseCmtRepository")
 */
class AdresseCmt
{

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */

    private $id;
    /**
     * @var String
     * @ORM\Column(name="adresse_cmt", type="string", length=255, nullable=true)
     */
    private $adresse_cmt;

    /**
     * @var String
     * @ORM\Column(name="adresse_cmt_ligne_2", type="string", length=255, nullable=true)
     */
    private $adresse_cmt_ligne_2;

    /**
     * @var String
     * @ORM\Column(name="adresse_cmt_ligne_3", type="string", length=255, nullable=true)
     */
    private $adresse_cmt_ligne_3;

    /**
     * @var String
     * @ORM\Column(name="code_postal_cmt", type="string", length=6, nullable=true)
     */
    private $code_postal_cmt;

    /**
     * @var String
     * @ORM\Column(name="ville_cmt", type="string", length=255, nullable=true)
     */
    private $ville_cmt;

    /**
     * @var String
     * @ORM\Column(name="latitude", type="string", length=50, nullable=true)
     */
    private $latitude_cmt;

    /**
     * @var String
     * @ORM\Column(name="longitude", type="string", length=50, nullable=true)
     */
    private $longitude_cmt;


    /**
     * Adresse constructor.
     */
    public function __construct()
    {

    }


    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return String
     */
    public function getAdresseCmt()
    {
        return $this->adresse_cmt;
    }

    /**
     * @param String $adresse_cmt
     */
    public function setAdresseCmt($adresse_cmt)
    {
        $this->adresse_cmt = $adresse_cmt;
    }

    /**
     * @return String
     */
    public function getAdresseCmtLigne2()
    {
        return $this->adresse_cmt_ligne_2;
    }

    /**
     * @param String $adresse_cmt_ligne_2
     */
    public function setAdresseCmtLigne2($adresse_cmt_ligne_2)
    {
        $this->adresse_cmt_ligne_2 = $adresse_cmt_ligne_2;
    }

    /**
     * @return String
     */
    public function getAdresseCmtLigne3()
    {
        return $this->adresse_cmt_ligne_3;
    }

    /**
     * @param String $adresse_cmt_ligne_3
     */
    public function setAdresseCmtLigne3($adresse_cmt_ligne_3)
    {
        $this->adresse_cmt_ligne_3 = $adresse_cmt_ligne_3;
    }

    /**
     * @return String
     */
    public function getCodePostalCmt()
    {
        return $this->code_postal_cmt;
    }

    /**
     * @param String $code_postal_cmt
     */
    public function setCodePostalCmt($code_postal_cmt)
    {
        $this->code_postal_cmt = $code_postal_cmt;
    }

    /**
     * @return String
     */
    public function getVilleCmt()
    {
        return $this->ville_cmt;
    }

    /**
     * @param String $ville_cmt
     */
    public function setVilleCmt($ville_cmt)
    {
        $this->ville_cmt = $ville_cmt;
    }

    /**
     * @return String
     */
    public function getLatitudeCmt()
    {
        return $this->latitude_cmt;
    }

    /**
     * @param String $latitude_cmt
     */
    public function setLatitudeCmt($latitude_cmt)
    {
        $this->latitude_cmt = $latitude_cmt;
    }

    /**
     * @return String
     */
    public function getLongitudeCmt()
    {
        return $this->longitude_cmt;
    }

    /**
     * @param String $longitude_cmt
     */
    public function setLongitudeCmt($longitude_cmt)
    {
        $this->longitude_cmt = $longitude_cmt;
    }

    /**
     * Method qui retourne adresse complete
     *
     * @return string
     */
    public function getFormattedAddress()
    {
        return $this->__toString();

    }

    /**
     * @return string
     */
    public function __toString()
    {
        return $this->getAdresseCmt() . "+" .
            $this->getAdresseCmtLigne2() . "+" .
            $this->getAdresseCmtLigne3() . "," .
            $this->getCodePostalCmt() . "," .
            $this->getVilleCmt() . ", France";
    }


}

GeoCodeurBundle/Controller/DefaultController.php
<?php

namespace GeoCodeurBundle\Controller;


use Doctrine\Common\Util\Debug;
use Doctrine\ORM\EntityManager;
use GeoCodeurBundle\Entity\AdresseCmt;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Lsw\ApiCallerBundle\Call\HttpGetJson;

/**
 * Class DefaultController
 * @package GeoCodeurBundle\Controller
 */
class DefaultController extends Controller
{

    public function sauvegarde()
    {
        /** @var EntityManager $em */
        $em = $this->getDoctrine()->getManager();
        $adress = $em->getRepository("GeoCodeurBundle:AdresseCmt")->findAll();
        foreach ($adress as $location) {
            /** @var AdresseCmt $location */
            $location = new AdresseCmt();
            $FormattedAddress = $location->getFormattedAddress();
            $_url = "http://maps.google.com/maps/api/geocode/json?sensor=true&address=" . urlencode($FormattedAddress) . "&sensor=false";

            $curl = curl_init();
            curl_setopt_array($curl, array(
                CURLOPT_RETURNTRANSFER => 1,
                CURLOPT_URL => $_url,
                CURLOPT_HTTPGET => 1,
                CURLOPT_HTTPHEADER => array(
                    'Content-Type: application/json',
                    'Accept: application/json'
                ),
                CURLOPT_USERAGENT => 'Codular Sample cURL Request'
            ));
            $resp = curl_exec($curl);
            $json = json_decode($resp, true);
            if (\array_key_exists('results', $json) && $json['results']) {

                $lati = $json['results'][0]['geometry']['location']['lat'];
                $longi = $json['results'][0]['geometry']['location']['lng'];

                $location->setLatitudeCmt($lati);
                $location->setLongitudeCmt($longi);

                $em->persist($location);
                $em->flush();
            }
        }
    }


    /**
     * @return \Symfony\Component\HttpFoundation\Response
     */
    public function indexAction()
    {

        $em = $this->getDoctrine()->getManager();
        $adresses = $em->getRepository("GeoCodeurBundle:AdresseCmt")->findAll();


        return $this->render('GeoCodeurBundle:Default:index.html.twig',
            array(
                "total" => count($adresses),
                'entities' => $adresses,
            ));

    }

}

GeoCodeurBundle/Tests/Controller/DefaultControllerTest.php
<?php

namespace GeoCodeurBundle\Tests\Controller;

use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

/**
 * Class DefaultControllerTest
 * @package GeoCodeurBundle\Tests\Controller
 */
class DefaultControllerTest extends WebTestCase
{
    public function testIndex()
    {
        $client = static::createClient();

        $crawler = $client->request('GET', '/hello/Fabien');

        $this->assertTrue($crawler->filter('html:contains("Hello Fabien")')->count() > 0);
    }
}

GeoCodeurBundle/Resources/views/Default/index.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    <meta charset="utf-8">
    <title>Complex icons</title>
    <style>
        #map_wrapper {
            height: 400px;
        }

        #map_canvas {
            width: 100%;
            height: 100%;
        }
    </style>

</head>
<body>
<div id="map_wrapper">
    <div id="map_canvas" class="mapping"></div>
</div>
<script type="text/javascript" src="{{ asset('bundles/cma/js/jquery.min.js') }}"></script>
<script type="application/javascript">
//    jQuery(function ($) {
//        // Asynchronously Load the map API
//        var script = document.createElement('script');
//        script.src = "//maps.googleapis.com/maps/api/js?sensor=false&callback=initialize";
//        document.body.appendChild(script);
//    });

    function initMap() {
        var map;
        var bounds = new google.maps.LatLngBounds();
        var mapOptions = {
            mapTypeId: 'roadmap'
        };

        // Display a map on the page
        map = new google.maps.Map(document.getElementById("map_canvas"), mapOptions);
        map.setTilt(45);

        // Multiple Markers
        var markers = [
            {% for entity in entities %}
            ['Place {{ entity.id }} ', {{ entity.latitudeCmt }}, {{ entity.longitudeCmt }}],
            {% endfor %}
        ];

//        // Info Window Content
        var infoWindowContent = [
            ['<div class="info_content">' +
            '<h3>London Eye</h3>' +
            '<p>The London Eye is a giant Ferris wheel situated on the banks of the River Thames. The entire structure is 135 metres (443 ft) tall and the wheel has a diameter of 120 metres (394 ft).</p>' + '</div>'],
            ['<div class="info_content">' +
            '<h3>Palace of Westminster</h3>' +
            '<p>The Palace of Westminster is the meeting place of the House of Commons and the House of Lords, the two houses of the Parliament of the United Kingdom. Commonly known as the Houses of Parliament after its tenants.</p>' +
            '</div>']
        ];

        // Display multiple markers on a map
        var infoWindow = new google.maps.InfoWindow(), marker, i;

        // Loop through our array of markers & place each one on the map
        for (i = 0; i < markers.length; i++) {
            var position = new google.maps.LatLng(markers[i][1], markers[i][2]);
            bounds.extend(position);
            marker = new google.maps.Marker({
                position: position,
                map: map,
                title: markers[i][0]
            });

            // Allow each marker to have an info window
            google.maps.event.addListener(marker, 'click', (function (marker, i) {
                return function () {
                    infoWindow.setContent(infoWindowContent[i][0]);
                    infoWindow.open(map, marker);
                }
            })(marker, i));

            // Automatically center the map fitting all markers on the screen
            map.fitBounds(bounds);
        }

        // Override our map zoom level once our fitBounds function runs (Make sure it only runs once)
        var boundsListener = google.maps.event.addListener((map), 'bounds_changed', function (event) {
            this.setZoom(14);
            google.maps.event.removeListener(boundsListener);
        });

    }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=YOUR_KEY_API&callback=initMap"
         ></script>
</body>
</html>